server {
  listen 80;

  location ~* \.(js|jpg|png|css)$ {
    proxy_pass https://amatiasq.github.io;
    rewrite /(.*) /soliluna/$1 break;
  }

  location / {
    proxy_pass https://amatiasq.github.io;
    rewrite /(.*) /soliluna/ break;
  }
}
