version: '3.5'

services:
  nginx:
    container_name: amq-soliluna
    image: nginx
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    environment:
      - VIRTUAL_HOST=soliluna.amatiasq.com
      - LETSENCRYPT_HOST=soliluna.amatiasq.com
      - LETSENCRYPT_EMAIL=amatiasq@gmail.com
    networks:
      - exposed

networks:
  exposed:
    external: true
